import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n
    .use(initReactI18next)
    .init({
    debug: true,
    fallbackLng: 'id',
    resources: {
        en: {
            translation: {
            navbar1: "Home",
            navbar2: "History",
            navbar3: "Vision & Mission",
            navbar4: "Company Value",
            navbar5: "Awards",
            navbar6: "Partner",
            berandaDesc: "An official distributor of various brands of medical devices and superior in service quality.",
            berandaBtn: "Start",
            beranda1: "Health Offices",
            beranda2: "Hospitals",
            beranda3: "Health Centre",
            beranda4: "Schools, Clinics, Etc",
            berandaQuote: "\"We believe that your satisfaction is Our top priority!\"",
            sekilasTitle: "Overview",
            sekilas1: "\"PT Sungadiman Makmur Sentosa is a company with dozens of years of experience in the distribution of medical devices as an official distributor of various brands of medical devices and excels in service quality.\"",
            sekilas2: "PT Sungadiman Makmur Sentosa upholds the principle of improving public health through services by upholding the quality of products sold and establishing partnerships with national-class medical device production companies that have an international reputation.",
            sejarahTitle: "Our History",
            sejarah1: "Started from a medical device retail store that runs with business partners.",
            sejarah2: "Decided to become an independent medical device retail store.",
            sejarah3: "Switched to medical devices distributor.",
            sejarah4: "Became a distributor with CDAKB Certification standards.",
            misiTitle: "Our Mission",
            misiDesc: "\"To become the main distributor company providing medical device products for people in Indonesia.\"",
            visiTitle: "Our Vision",
            visi1: "Customer Satisfaction",
            visi1Desc: "Satisfy consumers by focusing on product availability, variety and quality.",
            visi2: "Quality Service",
            visi2Desc: "Provide quality service by continuously improving the ability of human resources (HR) along with the times.",
            visi3: "Effective Systemization",
            visi3Desc: "Effective, efficient, convenient and integrated systemization with both offline and online.",
            nilaiTitle1: "Innovative",
            nilaiDesc1: "Always bring up new IDEA so that the company continues to grow.",
            nilaiTitle2: "Collaborative",
            nilaiDesc2: "Building synergistic cooperation with one another to create a solid team.",
            nilaiTitle3: "Harmonious",
            nilaiDesc3: "Mutual care and respect in building a conducive work environment.",
            nilaiTitle4: "Loyalty",
            nilaiDesc4:  "Dedicated and prioritizing common interests and willing to make sacrifices to achieve greater goals.",
            nilaiTitle5: "Trust",
            nilaiDesc5: "Hold fast the trust given and be responsible for fulfilling promises and commitments.",
            nilaiTitle6: "Solutive",
            nilaiDesc6: "Always provide solutions and input to problems that exist in each team, so that they are resolved immediately.",
            nilaiTitle: "Company Value",
            penghargaanTitle: "Awards",
            alamat: "Address",
            telepon: "Phone"
            }
        },
        id: {
            translation: {
            navbar1: "Beranda",
            navbar2: "Sejarah",
            navbar3: "Visi & Misi",
            navbar4: "Nilai Perusahaan",
            navbar5: "Penghargaan",
            navbar6: "Partner",
            berandaDesc: "Distributor resmi berbagai brand alat kesehatan dan unggul dalam kualitas jasa pelayanan.",
            berandaBtn: "Mulai",
            beranda1: "Dinas Kesehatan",
            beranda2: "Rumah Sakit",
            beranda3: "Puskesmas",
            beranda4: "Sekolah, Klinik, Dll",
            berandaQuote: "\"Kami percaya jika kepuasan Anda adalah prioritas utama kami!\"",
            sekilasTitle: "Sekilas",
            sekilas1: "\"PT Sungadiman Makmur Sentosa merupakan perusahaan yang berpengalaman selama belasan tahun dalam bidang distribusi alat kesehatan sebagai distributor resmi berbagai brand alat kesehatan dan unggul dalam kualitas jasa pelayanan.\"",
            sekilas2: "PT Sungadiman Makmur Sentosa berpegang teguh pada prinsip usaha peningkatan kesehatan masyarakat melalui jasa pelayanan dengan menjunjung tinggi kualitas produk yang di jual dan menjalin kemitraan dengan perusahaan produksi alat kesehatan kelas nasional yang memiliki reputasi dikancah internasional.",
            sejarahTitle: "Sejarah PT. Sungadiman Makmur Sentosa",
            sejarah1: "Berawal dari toko retail alat kesehatan yang dijalankan dengan partner bisnis.",
            sejarah2: "Memutuskan untuk menjadi toko retail alat kesehatan yang mandiri.",
            sejarah3: "Beralih menjadi distributor alat kesehatan.",
            sejarah4: "Menjadi distributor dengan standar Sertifikasi CDAKB.",
            misiTitle: "Misi Kami",
            misiDesc: "\"Menjadi Perusahaan Distributor Utama Penyedia Produk Alat Kesehatan Bagi Seluruh Masyarakat Di Indonesia.\"",
            visiTitle: "Visi Kami",
            visi1: "Kepuasan Konsumen",
            visi1Desc: "Memberikan kepuasan kepada konsumen dengan terfokus padaketersediaan, variasi & kualitas produk.",
            visi2: "Pelayanan Berkualitas",
            visi2Desc: "Memberikan pelayanan yang berkualitas dengan senantiasa meningkatkan kemampuan sumber daya manusia (SDM) seiring perkembangan zaman.",
            visi3: "Sistemisasi Efektif",
            visi3Desc: "Sistemisasi yang efektif, efisien, nyaman dan terintegrasi baik secara offline maupun online.",
            nilaiTitle1: "Inovatif",
            nilaiDesc1: "Senantiasa memunculkan sesuatu IDE yang baru agar perusahaan terus bertumbuh.",
            nilaiTitle2: "Kolaboratif",
            nilaiDesc2: "Membangun kerjasama yang sinergis antara satu dengan lainya untuk menciptakan team yang solid.",
            nilaiTitle3: "Harmonis",
            nilaiDesc3: "Saling peduli dan menghargai dalam membangun lingkungan kerja yang kondusif.",
            nilaiTitle4: "Loyalitas",
            nilaiDesc4:  "Berdedikasi dan mengutamakan kepentingan bersama dan rela berkorban untuk mencapai tujuan yang lebih besar.",
            nilaiTitle5: "Amanah",
            nilaiDesc5: "Memegang teguh kepercayaan yang diberikan serta bertanggung jawab memenuhi janji dan komitmen.",
            nilaiTitle6: "Solutif",
            nilaiDesc6: "Senantiasa memberikan solusi dan  masukan atas permasalahan permasalahan yang ada disetiap team, supaya segera terselesaikan.",
            nilaiTitle: "Nilai Perusahaan",
            penghargaanTitle: "Penghargaan",
            alamat: "Alamat",
            telepon: "Telepon"
            },
        },
    }
    });

export default i18n;